customhost = "databasepro2.cnyh4lakhyrg.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "databasepro2"
custombucket = "vproject2bucket"
customregion = "us-east-1"
